env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - binary: go-serve
    main: ./cmd/server/main.go
    flags:
      - -trimpath
      - -tags=timetzdata
    ldflags:
      - -s -w -X go.eloylp.dev/go-serve/server.Name=go-serve -X go.eloylp.dev/go-serve/server.Version={{.Version}} -X go.eloylp.dev/go-serve/server.Build={{.ShortCommit}} -X go.eloylp.dev/go-serve/server.BuildTime={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - amd64
      - arm
      - arm64
      - mips
      - mips64
    goarm:
      - 7
      - 6
      - 5
    ignore:
      - goos: darwin
        goarch: 386
      - goos: openbsd
        goarch: arm
      - goos: freebsd
        goarch: arm
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    id: go-serve
    format: binary

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
